// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: plot.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// one server, many clients....
type ClientReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*ClientReq_Msg
	//	*ClientReq_Id
	Request isClientReq_Request `protobuf_oneof:"Request"`
}

func (x *ClientReq) Reset() {
	*x = ClientReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReq) ProtoMessage() {}

func (x *ClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReq.ProtoReflect.Descriptor instead.
func (*ClientReq) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{0}
}

func (m *ClientReq) GetRequest() isClientReq_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ClientReq) GetMsg() *ClientMSG {
	if x, ok := x.GetRequest().(*ClientReq_Msg); ok {
		return x.Msg
	}
	return nil
}

func (x *ClientReq) GetId() int32 {
	if x, ok := x.GetRequest().(*ClientReq_Id); ok {
		return x.Id
	}
	return 0
}

type isClientReq_Request interface {
	isClientReq_Request()
}

type ClientReq_Msg struct {
	Msg *ClientMSG `protobuf:"bytes,1,opt,name=msg,proto3,oneof"`
}

type ClientReq_Id struct {
	Id int32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

func (*ClientReq_Msg) isClientReq_Request() {}

func (*ClientReq_Id) isClientReq_Request() {}

type ClientMSG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClientMSG) Reset() {
	*x = ClientMSG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMSG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMSG) ProtoMessage() {}

func (x *ClientMSG) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMSG.ProtoReflect.Descriptor instead.
func (*ClientMSG) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMSG) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ClientMSG) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServerRES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *ClientMSG `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Id  int32      `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServerRES) Reset() {
	*x = ServerRES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRES) ProtoMessage() {}

func (x *ServerRES) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRES.ProtoReflect.Descriptor instead.
func (*ServerRES) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{2}
}

func (x *ServerRES) GetMsg() *ClientMSG {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerRES) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_plot_proto protoreflect.FileDescriptor

var file_plot_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x09,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x53, 0x47, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x53, 0x47, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a,
	0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x45, 0x53, 0x12, 0x1c, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x53, 0x47, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0x2d, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x04, 0x56, 0x6f, 0x49, 0x50, 0x12, 0x0a, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x53, 0x47, 0x1a, 0x0a, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x45, 0x53, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plot_proto_rawDescOnce sync.Once
	file_plot_proto_rawDescData = file_plot_proto_rawDesc
)

func file_plot_proto_rawDescGZIP() []byte {
	file_plot_proto_rawDescOnce.Do(func() {
		file_plot_proto_rawDescData = protoimpl.X.CompressGZIP(file_plot_proto_rawDescData)
	})
	return file_plot_proto_rawDescData
}

var file_plot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plot_proto_goTypes = []interface{}{
	(*ClientReq)(nil), // 0: ClientReq
	(*ClientMSG)(nil), // 1: ClientMSG
	(*ServerRES)(nil), // 2: ServerRES
}
var file_plot_proto_depIdxs = []int32{
	1, // 0: ClientReq.msg:type_name -> ClientMSG
	1, // 1: ServerRES.msg:type_name -> ClientMSG
	1, // 2: Calling.VoIP:input_type -> ClientMSG
	2, // 3: Calling.VoIP:output_type -> ServerRES
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plot_proto_init() }
func file_plot_proto_init() {
	if File_plot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMSG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_plot_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientReq_Msg)(nil),
		(*ClientReq_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plot_proto_goTypes,
		DependencyIndexes: file_plot_proto_depIdxs,
		MessageInfos:      file_plot_proto_msgTypes,
	}.Build()
	File_plot_proto = out.File
	file_plot_proto_rawDesc = nil
	file_plot_proto_goTypes = nil
	file_plot_proto_depIdxs = nil
}
