version: '3'
services:
  gonb:
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - 8888:8888
    
  mysql:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: "0x113c1c3"
    ports:
      - "3308:3308"
 
